const ICONS = {
  home: "⌂",
  user: "◉",
  images: "▧",
  "mail-open": "✉",
  comments: "◌",
  sun: "☼",
  moon: "◐",
  "arrow-left": "←",
  "arrow-right": "→",
  facebook: "f",
  twitter: "x",
  linkedin: "in",
  alert: "!",
  "check-circle": "✓",
  media: "▣",
  quote: "“",
  link: "↗",
  close: "×",
  drag: "⋮",
  upload: "↑",
  like: "♡",
  reply: "↩",
  heart: "♥",
  "heart-outline": "♡",
  check: "✓",
  chart: "⌁",
  file: "▤",
  pen: "✎",
  address: "▣",
  shield: "◈",
  newspaper: "▥",
  layers: "▦",
  share: "↗",
  send: "➤",
  reset: "↺",
  save: "✓",
  trash: "⌫",
  "cloud-upload": "↑",
  warning: "!",
  restore: "↺",
  "comment-dots": "…",
  paragraph: "≡",
  pin: "⌖",
  clock: "◷",
  edit: "✎",
  eye: "◉",
  "eye-off": "◌",
  info: "i",
  logout: "↪",
  "id-card": "▣",
  lock: "▣",
  mail: "✉",
  key: "⚿",
  image: "▧",
  plus: "+",
  external: "↗",
};

export default function Icon({ icon, label, className = "" }) {
  return (
    <span className={`app_icon ${className}`.trim()} aria-hidden={label ? undefined : "true"} aria-label={label}>
      {ICONS[icon] || "•"}
    </span>
  );
}
